tag: s3base

files:
  sim_grid: /data/project/general/DeepLearningCP/data/KiDS450_CNN_Analysis/data/Simulation_Shells/KiDS450_new_run/KiDs450_new_grid
  nz: /data/user/kacprz_t/projects/211027_combined_lss_ai/redshift_distributions/
  projected_maps: /shared-scratch/kacprz_t/data/projected_maps_stage3nonorm/
  astro_prior_grid: /shared-scratch/kacprz_t/data/astrosamples_n9/
  poisson_generator: /shared-scratch/kacprz_t/poiss_gen/

params_astro_const:
  ng_eff: 2.5 # number of galaxies per arcmin^2  3879823 2990099 2970570 2687130
  sigma_e: 0.4 # galaxy shape+measurement noise
  map_patch_size_deg: 5 # size of the image side in degrees
  galaxy_counts_noise_model: stochasticity
  z_ia_pivot: 0.7
  z_bg_pivot: 0.7

analysis_settings:
  probes: ['kg', 'dg'] # full set 'kg', 'dg'] 
  redshift_bins: [0,1,2,3] # bin4 is the total
  n_grid_theta_astro: 5000
  n_samples: 128000
  sampler: emcee
  params_sim: params_stage3mosaic_npix64

training:
  batch_size: 20
  n_batches_per_epoch: 1000
  n_epochs: 100
  transform_theta: S8
  neff_decay_n0: 0 # set 0 for no augmentation
  neff_decay_half_time: 20000
  transform_maps: True
  mosaic: True

priors:
  # omega_m is on a precomputed simulation grid 0
  # sigma_8 is on a precomputed simulation grid 1
  A_IA: [0.5, -6, 6] 
  b_gal: [1.5, 0.5, 2.5] 
  r_stoch: [0.7, 0.4, 1] 
  alpha0_spoiss: 1.0 
  alpha1_spoiss: 0.0 
  eta_A_IA: [1.6, -4, 6]
  eta_b_gal: [0.5, -3, 3]
  b2_gal: 0
  eta_b2_gal: 0

likelihood_modelling:
  n_epochs: 1000
  batch_size: 1000
  likenet:
    n_gaussians: 3


lssnets:

    - name: kg_cnn
      model: lsscnn
      probes: kg
      smoothing_sigma_arcmin: [4.778, 3.509, 2.758, 2.526] # apply Gaussian smoothing (sigma in arcmin)
      learning_rate: 0.00005
      grad_clip_percentile: 50
      normalization: null # [null, batch_norm, layer_norm]
      kernel_size: 5
      n_conv_layers: 4
      n_res_layers: 10
      filters: 128

    - name: kg_psd
      model: lsspsd
      probes: kg
      smoothing_sigma_arcmin: [4.778, 3.509, 2.758, 2.526] # apply Gaussian smoothing (sigma in arcmin)
      learning_rate: 0.0005
      grad_clip_percentile: 50
      ells: [36, 4536, 20]
      kernel_size: 3
      n_conv_layers: 2
      n_res_layers: 0
      filters: 1024
      arch: classic


    - name: dg_cnn
      model: lsscnn
      probes: dg
      smoothing_sigma_arcmin: [9.839, 7.398, 5.991, 5.567] # apply Gaussian smoothing (sigma in arcmin)
      learning_rate: 0.00005
      grad_clip_percentile: 50
      normalization: null # [null, batch_norm, layer_norm]
      kernel_size: 5
      n_conv_layers: 4
      n_res_layers: 10
      filters: 128

    - name: dg_psd
      model: lsspsd
      probes: dg
      smoothing_sigma_arcmin: [9.839, 7.398, 5.991, 5.567] # apply Gaussian smoothing (sigma in arcmin)
      learning_rate: 0.0005
      grad_clip_percentile: 50
      ells: [36, 4536, 20]
      kernel_size: 3
      n_conv_layers: 2
      n_res_layers: 0
      filters: 1024
      arch: classic


    - name: cp_cnn
      model: lsscnn
      probes: cp
      smoothing_sigma_arcmin: [4.778, 3.509, 2.758, 2.526, 9.839, 7.398, 5.991, 5.567] # apply Gaussian smoothing (sigma in arcmin)
      learning_rate: 0.00005
      grad_clip_percentile: 50
      normalization: null # [null, batch_norm, layer_norm]
      kernel_size: 5
      n_conv_layers: 4
      n_res_layers: 10
      filters: 128

    - name: cp_psd
      model: lsspsd
      probes: cp
      smoothing_sigma_arcmin: [4.778, 3.509, 2.758, 2.526, 9.839, 7.398, 5.991, 5.567] # apply Gaussian smoothing (sigma in arcmin)
      learning_rate: 0.0005
      grad_clip_percentile: 50
      ells: [36, 4536, 20]
      kernel_size: 3
      n_conv_layers: 2
      n_res_layers: 0
      filters: 1024
      arch: classic
